/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CollectionRouteImport } from './routes/collection'
import { Route as FitRouteImport } from './routes/fit'
import { Route as IronsyncRouteImport } from './routes/ironsync'
import { Route as SupportRouteImport } from './routes/support'
import { Route as WatchesSlugRouteImport } from './routes/watches.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionRoute = CollectionRouteImport.update({
  id: '/collection',
  path: '/collection',
  getParentRoute: () => rootRouteImport,
} as any)
const FitRoute = FitRouteImport.update({
  id: '/fit',
  path: '/fit',
  getParentRoute: () => rootRouteImport,
} as any)
const IronsyncRoute = IronsyncRouteImport.update({
  id: '/ironsync',
  path: '/ironsync',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchesSlugRoute = WatchesSlugRouteImport.update({
  id: '/watches/$slug',
  path: '/watches/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/collection': typeof CollectionRoute
  '/fit': typeof FitRoute
  '/ironsync': typeof IronsyncRoute
  '/support': typeof SupportRoute
  '/watches/$slug': typeof WatchesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/collection': typeof CollectionRoute
  '/fit': typeof FitRoute
  '/ironsync': typeof IronsyncRoute
  '/support': typeof SupportRoute
  '/watches/$slug': typeof WatchesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/collection': typeof CollectionRoute
  '/fit': typeof FitRoute
  '/ironsync': typeof IronsyncRoute
  '/support': typeof SupportRoute
  '/watches/$slug': typeof WatchesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/collection' | '/fit' | '/ironsync' | '/support' | '/watches/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/collection' | '/fit' | '/ironsync' | '/support' | '/watches/$slug'
  id:
    | '__root__'
    | '/'
    | '/collection'
    | '/fit'
    | '/ironsync'
    | '/support'
    | '/watches/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CollectionRoute: typeof CollectionRoute
  FitRoute: typeof FitRoute
  IronsyncRoute: typeof IronsyncRoute
  SupportRoute: typeof SupportRoute
  WatchesSlugRoute: typeof WatchesSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection': {
      id: '/collection'
      path: '/collection'
      fullPath: '/collection'
      preLoaderRoute: typeof CollectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fit': {
      id: '/fit'
      path: '/fit'
      fullPath: '/fit'
      preLoaderRoute: typeof FitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ironsync': {
      id: '/ironsync'
      path: '/ironsync'
      fullPath: '/ironsync'
      preLoaderRoute: typeof IronsyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watches/$slug': {
      id: '/watches/$slug'
      path: '/watches/$slug'
      fullPath: '/watches/$slug'
      preLoaderRoute: typeof WatchesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CollectionRoute: CollectionRoute,
  FitRoute: FitRoute,
  IronsyncRoute: IronsyncRoute,
  SupportRoute: SupportRoute,
  WatchesSlugRoute: WatchesSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
